const exit = {
  entryNumber: "",
  driver: {
    name: "",
    cedula: "",
    code: "",
    originID: 0,
  },
  vehicule: {
    id: "",
    plate: "",
    model: "",
    type: "",
    capacity: 0,
    company: "",
    companyID: "",
    originID: 0,
  },
  action: 1,
  destination: "D01",
  operation: "",
  entryDate: "",
  exitDate: "",
  origin: "",
  truckWeight: 0,
  grossWeight: 0,
  calculatedNetWeight: 0,
  netWeight: 0,
  invoice: null,
  entryDetails: "",
  distDetails: "",
  exitDetails: "",
  palletWeight: 0,
  palletsQuatity: 0,
  aditionalWeight: 0,
  weightDifference: 0,
  userAccountName: "",
  aboutToLeave: false,
}