export const distEntriesExamples: P_ENT_DI[] = [
  {
    ENT_NUM: '95557',
    USU_LOG: 'rumendez',
    ENT_DI_FEC: '2024-03-15T19:12:37.637Z',
    ENT_DI_PRO: 'BARCELONA ',
    ENT_DI_GUI: null,
    ENT_DI_PNC: null,
    ENT_DI_CPA: 0,
    ENT_DI_PPA: null,
    ENT_DI_PLA: null,
    ENT_DI_DES: null,
    ENT_DI_PAD: 0,
    ENT_DI_DPA: null,
    ENT_DI_STA: null,
    ENT_DI_AUT: null,
    ENT_DI_NDE: null,
    ENT_DI_PAL: null,
    ENT_DI_OBS: null,
    ENT_DI_REV: false,
  },
  {
    ENT_NUM: '95555',
    USU_LOG: 'rumendez',
    ENT_DI_FEC: '2024-03-15T18:15:27.947Z',
    ENT_DI_PRO: 'VALENCIA ',
    ENT_DI_GUI: null,
    ENT_DI_PNC: null,
    ENT_DI_CPA: 0,
    ENT_DI_PPA: null,
    ENT_DI_PLA: null,
    ENT_DI_DES: null,
    ENT_DI_PAD: 0,
    ENT_DI_DPA: null,
    ENT_DI_STA: null,
    ENT_DI_AUT: null,
    ENT_DI_NDE: null,
    ENT_DI_PAL: null,
    ENT_DI_OBS: null,
    ENT_DI_REV: false,
  },
  {
    ENT_NUM: '95552',
    USU_LOG: 'rumendez',
    ENT_DI_FEC: '2024-03-15T19:10:05.070Z',
    ENT_DI_PRO: 'GUACARA',
    ENT_DI_GUI: null,
    ENT_DI_PNC: null,
    ENT_DI_CPA: 0,
    ENT_DI_PPA: null,
    ENT_DI_PLA: null,
    ENT_DI_DES: null,
    ENT_DI_PAD: 0,
    ENT_DI_DPA: null,
    ENT_DI_STA: null,
    ENT_DI_AUT: null,
    ENT_DI_NDE: null,
    ENT_DI_PAL: null,
    ENT_DI_OBS: null,
    ENT_DI_REV: false,
  },
  {
    ENT_NUM: '95551',
    USU_LOG: 'rumendez',
    ENT_DI_FEC: '2024-03-15T18:27:15.187Z',
    ENT_DI_PRO: 'CARACAS',
    ENT_DI_GUI: null,
    ENT_DI_PNC: null,
    ENT_DI_CPA: 0,
    ENT_DI_PPA: null,
    ENT_DI_PLA: null,
    ENT_DI_DES: null,
    ENT_DI_PAD: 0,
    ENT_DI_DPA: null,
    ENT_DI_STA: null,
    ENT_DI_AUT: null,
    ENT_DI_NDE: null,
    ENT_DI_PAL: null,
    ENT_DI_OBS: null,
    ENT_DI_REV: false,
  },
]

export const entriesExamples: P_ENT[] = [
  {
    ENT_NUM: '95557',
    ENT_FEC: '2024-03-15T15:44:26.700Z',
    USU_LOG: 'USR9509C',
    VEH_ID: '11639',
    CON_COD: '120001',
    DES_COD: 'D01',
    OPE_COD: 'OO9',
    ENT_PES_TAR: 7280,
    EMP_ID: null,
    ENT_OBS: null,
    ENT_FLW: 2,
    ENT_FEC_COL: null,
    ENT_FLW_ACC: 1,
  },
  {
    ENT_NUM: '95555',
    ENT_FEC: '2024-03-15T15:38:31.633Z',
    USU_LOG: 'USR9509C',
    VEH_ID: '6733',
    CON_COD: '218957',
    DES_COD: 'D01',
    OPE_COD: 'OO9',
    ENT_PES_TAR: 14920,
    EMP_ID: null,
    ENT_OBS: null,
    ENT_FLW: 2,
    ENT_FEC_COL: null,
    ENT_FLW_ACC: 1,
  },
  {
    ENT_NUM: '95552',
    ENT_FEC: '2024-03-15T15:23:17.290Z',
    USU_LOG: 'USR9509C',
    VEH_ID: '10043',
    CON_COD: '217946',
    DES_COD: 'D01',
    OPE_COD: 'OO9',
    ENT_PES_TAR: 3800,
    EMP_ID: null,
    ENT_OBS: null,
    ENT_FLW: 2,
    ENT_FEC_COL: null,
    ENT_FLW_ACC: 1,
  },
  {
    ENT_NUM: '95551',
    ENT_FEC: '2024-03-15T15:22:11.517Z',
    USU_LOG: 'USR9509C',
    VEH_ID: '8033',
    CON_COD: '218978',
    DES_COD: 'D01',
    OPE_COD: 'OO9',
    ENT_PES_TAR: 4110,
    EMP_ID: null,
    ENT_OBS: null,
    ENT_FLW: 2,
    ENT_FEC_COL: null,
    ENT_FLW_ACC: 1,
  },
]